# Generated by Django 5.2.7 on 2025-11-03 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('fechaEvento', models.DateField(unique=True)),
                ('numInvitados', models.PositiveSmallIntegerField(help_text='1 a 50 invitados permitidos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada')], default='pendiente', max_length=10)),
                ('tipoEvento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservaciones.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcionDuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.opcionduracion')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.reservacion')),
            ],
            options={
                'unique_together': {('reservacion', 'opcionDuracion')},
            },
        ),
    ]
