# Generated by Django 5.2.7 on 2025-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='tipoEvento',
            field=models.CharField(choices=[('cumpleaños', 'Cumpleaños'), ('boda', 'Boda'), ('xv', 'XV Años'), ('infantil', 'Evento Infantil'), ('corporativo', 'Evento Corporativo'), ('otro', 'Otro')], default='cumpleaños', max_length=20),
        ),
        migrations.DeleteModel(
            name='TipoEvento',
        ),
    ]
