# Generated by Django 5.2.7 on 2025-11-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_alter_reservacion_tipoevento_delete_tipoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fechaEvento',
            field=models.DateField(),
        ),
    ]
