# Generated by Django 5.2.7 on 2025-11-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_alter_reservacion_fechaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='tipoEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservaciones.tipoevento'),
        ),
    ]
