# Generated by Django 5.2.7 on 2025-11-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionDuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(choices=[('00:30', '30 Minutos'), ('01:00', '1 Hora'), ('01:30', '1 Hora y 30 minutos'), ('02:00', '2 Horas')], max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='shows.show')),
            ],
        ),
    ]
