# Generated by Django 5.2.7 on 2025-11-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opcionduracion',
            unique_together={('show', 'duracion')},
        ),
    ]
