# Generated by Django 5.2.7 on 2025-11-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_opcionduracion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
